### ISSUE TITLE
Possible to run this UI and backend component on own infrastructure?

### ISSUE THREAD

**Issue by timmolter** [polkascan/explorer-ui#2]
Hello, can I run polkascan and its supporting services myself? Something like what polkascan.io provides: give it an account and it lists the TX history for example: https://polkascan.io/polkadot/account/16ZL8yLyXv3V3L3z9ofR1ovFLziyXaN1DPq4yffMAZ9czzBD I'd like to download and install such an explorer on my own infrastructure. And I don't necessarily need the UI, but only a REST API. I looked through the various repos here, but didn't find clear answers.

Is there an "indexer" component that polls a DOT node, populates a DB, and provides an API to clients needing information such as account TX history, current block chain height, account balances etc.?

**Comment by arjanz** [comment]
This particular repository is not ready for public use yet, you can have a look at https://github.com/polkascan/polkascan-os which contains the open-source version of the stack used at polkascan.io

**Comment by emielvanderhoek** [comment]
@timmolter allowing the public to run the full explorer stack themselves is one of the key milestones for early 2022, hopefully Q1.
We still need to open-source our new Substrate Harvester and the Docker Compose artifacts to allow for this.

**Comment by wouterter** [comment]
Running the entire Polkascan stack yourself is now possible:

https://github.com/polkascan/explorer
