### ISSUE TITLE
pageSize is interchanged with blockLimit

### ISSUE THREAD

**Issue by matthijsb** [polkascan/explorer-ui#23]
See for example this account:

https://explorer-dev.polkascan.io/polkadot/account/16hp43x8DUZtU8L3cJy9Z8JMwTzuu8ZZRWqDZnpMhp464oEd

It creates this query, which uses the blockLimit for the pageSize :

`query {
      getEventsByAccount( filters: { accountId: "0xfc4d6069cb980fcde6ef73a46f1894d66c152e9ddfac3a499cf6a1654ff5f55b" }, pageSize: 500000, blockLimitOffset: 13053521 ) {
        objects {
          blockNumber, eventIdx, attributeName, accountId, attributes, pallet, eventName, blockDatetime, sortValue, extrinsicIdx
        }, pageInfo { pageSize, pageNext, pagePrev, blockLimitOffset, blockLimitCount }
      }
    }`

**Comment by arjanz** [comment]
This results in retrieving a page of 500000 items and causes a query-timeout or a browser freeze
